"""fix_user_table_schema_mismatch

Revision ID: 0c6e6d138d0e
Revises: 46c0cd2559b5
Create Date: 2025-08-02 15:47:53.933346

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0c6e6d138d0e'
down_revision = '46c0cd2559b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Keeping item table as it may be used by other parts of the application
    # op.drop_table('item')
    
    # Rename full_name to name and set default values
    op.alter_column('user', 'full_name', new_column_name='name')
    op.alter_column('user', 'name', nullable=False)
    
    # Add missing columns
    op.add_column('user', sa.Column('major', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('class_', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='user'))
    op.add_column('user', sa.Column('permissions', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    
    # Create index for name column
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    
    # Remove obsolete columns
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back obsolete columns
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    
    # Drop index
    op.drop_index(op.f('ix_user_name'), table_name='user')
    
    # Drop new columns
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'permissions')
    op.drop_column('user', 'role')
    op.drop_column('user', 'class_')
    op.drop_column('user', 'major')
    
    # Rename name back to full_name
    op.alter_column('user', 'name', new_column_name='full_name')
    op.alter_column('user', 'full_name', nullable=True)
    # ### end Alembic commands ###
