"""add_id_troy_to_user_table

Revision ID: 46c0cd2559b5
Revises: 1a31ce608336
Create Date: 2025-08-02 15:45:34.975435

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '46c0cd2559b5'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_troy', sa.String(), nullable=False, server_default='000000'))
    op.create_index(op.f('ix_user_id_troy'), 'user', ['id_troy'], unique=True)
    op.alter_column('user', 'id_troy', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id_troy'), table_name='user')
    op.drop_column('user', 'id_troy')
    # ### end Alembic commands ###
